name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        ports: ['5432:5432']
        env: 
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.11.2' # Define the elixir version [required]
        otp-version: '24' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      working-directory: ./rockelivery
      run: mix deps.get
    - name: Check Formatting
      working-directory: ./rockelivery
      run: mix format --check-formatted
    - name : Run Credo
      working-directory: ./rockelivery
      run: mix credo --strict
    - name : Check coverage
      working-directory: ./rockelivery
      run: mix coveralls.json
      env:
        MIX_ENV: test
    - name : Run codecov script
      working-directory: ./rockelivery
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN}}
    - name: Run tests
      working-directory: ./rockelivery
      run: mix test

  deploy:
    needs: build # Will only run if the test job succeeds
    if: github.ref == 'refs/heads/master' # Only run this job if it is on the main branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            ref: master # Check out main instead of the latest commit
            fetch-depth: 0 # Checkout the whole branch
      - run: git remote add gigalixir https://git.gigalixir.com/${{ secrets.GIGALIXIR_APP_NAME }}.git
      - run: git subtree push gigalixir HEAD:refs/heads/master
        
          
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.1
    
      - uses: mhanberg/gigalixir-action@v0.4.0
        with:
          APP_SUBFOLDER: rockelivery/rockelivery  # Add only if you want to deploy an app that is not at the root of your repository
          GIGALIXIR_APP: elementary-perfect-rhea # Feel free to also put this in your secrets
          GIGALIXIR_CLEAN: true # defaults to false
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          MIGRATIONS: false  # defaults to true
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}